### PR TITLE
Support HSL.jl v0.4.1

### PR DESCRIPTION
**Pull request by amontoison**

### CODE REVIEW

**Comment by geoffroyleconte** [comment]
Thanks @amontoison! Are the tests passing locally? I don't think HSL is in the CI.

**Comment by amontoison** [comment]
@geoffroyleconte 
I completely forgot to finalize this PR.
I propose to wait the new release of libHSL (the new name of JuliaHSL).

**Comment by geoffroyleconte** [comment]
Hi @amontoison , I tested this locally but I have this error:

```
ERROR: LoadError: could not load symbol "JULIAHSL_isfunctional":
The specified procedure could not be found.
Stacktrace:
  [1] JULIAHSL_isfunctional()
    @ HSL C:\Users\Geoffroy Leconte\.julia\packages\HSL\u7tG8\src\C\juliahsl.jl:2
  [2] top-level scope
    @ C:\Users\Geoffroy Leconte\.julia\dev\RipQP\src\iterations\solvers\sparse_fact_utils\abstract-factorization.jl:83
  [3] include(mod::Module, _path::String)
    @ Base .\Base.jl:419
  [4] include(x::String)
    @ RipQP C:\Users\Geoffroy Leconte\.julia\dev\RipQP\src\RipQP.jl:1
  [5] top-level scope
    @ C:\Users\Geoffroy Leconte\.julia\dev\RipQP\src\iterations\iterations.jl:1
  [6] include(mod::Module, _path::String)
    @ Base .\Base.jl:419
  [7] include(x::String)
    @ RipQP C:\Users\Geoffroy Leconte\.julia\dev\RipQP\src\RipQP.jl:1
  [8] top-level scope
    @ C:\Users\Geoffroy Leconte\.julia\dev\RipQP\src\RipQP.jl:31
  [9] include
    @ .\Base.jl:419 [inlined]
 [10] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::String)
    @ Base .\loading.jl:1554
 [11] top-level scope
    @ stdin:1
in expression starting at C:\Users\Geoffroy Leconte\.julia\dev\RipQP\src\iterations\solvers\sparse_fact_utils\abstract-factorization.jl:83 
in expression starting at C:\Users\Geoffroy Leconte\.julia\dev\RipQP\src\iterations\iterations.jl:1
in expression starting at C:\Users\Geoffroy Leconte\.julia\dev\RipQP\src\RipQP.jl:1
in expression starting at stdin:1
ERROR: LoadError: Failed to precompile RipQP [1e40b3f8-35eb-4cd8-8edd-3e515bb9de08] to C:\Users\Geoffroy Leconte\.julia\compiled\v1.8\RipQP\jl_4C98.tmp.
Stacktrace:
  [1] error(s::String)
    @ Base .\error.jl:35
  [2] compilecache(pkg::Base.PkgId, path::String, internal_stderr::IO, internal_stdout::IO, keep_loaded_modules::Bool)
    @ Base .\loading.jl:1707
  [3] compilecache
    @ .\loading.jl:1651 [inlined]
  [4] _require(pkg::Base.PkgId)
    @ Base .\loading.jl:1337
  [5] _require_prelocked(uuidkey::Base.PkgId)
    @ Base .\loading.jl:1200
  [6] macro expansion
    @ .\loading.jl:1180 [inlined]
  [7] macro expansion
    @ .\lock.jl:223 [inlined]
  [8] require(into::Module, mod::Symbol)
    @ Base .\loading.jl:1144
  [9] include(fname::String)
    @ Base.MainInclude .\client.jl:476
 [10] top-level scope
    @ none:6
in expression starting at C:\Users\Geoffroy Leconte\.julia\dev\RipQP\test\runtests.jl:4
ERROR: Package RipQP errored during testing
```

**Comment by amontoison** [comment]
Hi @geoffroyleconte!
You need to replace `JULIAHSL_isfunctional()` by `LIBHSL_isfunctional()`.

**Comment by amontoison** [comment]
It should be good now Geoffroy.

**Comment by geoffroyleconte** [comment]
Thank you!

**Comment by amontoison** [comment]
@dpo Is it possible to upload th new libHSL / HSL_jll.jl on the Apple M1 for CI?

**Pull request merged**
