### PR TITLE
Test Float16

### PR DESCRIPTION
**Pull request by geoffroyleconte**

### CODE REVIEW

**Comment by geoffroyleconte** [comment]
@tmigot this should fix https://github.com/JuliaSmoothOptimizers/RipQP.jl/issues/140 for the easiest problems in `Float16`
You will have to lower the stopping criteria, for example:
```julia
stats = ripqp(qm, itol = InputTol(ϵ_pdd = 1.0e-1, ϵ_rb = 1.0e-1, ϵ_rc = 1.0e-1))
```

**Review by tmigot — APPROVED** [review]
Thanks @geoffroyleconte ! It seems to be solving my problem.

Would it make sense to have a default `InputTol` depending on the DataType?
Someting like `InputTol(::T; ϵ_pdd = sqrt(eps(T)), ...) where T ` ?

**Comment by geoffroyleconte** [comment]
@tmigot I want to keep the default Float64 stop criteria but I added new default values for other types based on your suggestion, is that ok ?

**Comment by tmigot** [comment]
Awesome! Thanks

**Pull request merged**
