### PR TITLE
HSL MA57 and MA97 CI

### PR DESCRIPTION
**Pull request by geoffroyleconte**

### CODE REVIEW

**Comment by geoffroyleconte** [comment]
@amontoison do you know why the tests with ma97 fail on julia 1.6? Here is the error message:
```
Got exception outside of a @test
  could not load library "/Users/administrator/.julia/packages/HSL/X5ozr/deps/usr/lib/libhsl_ma97.dylib"
  dlopen(/Users/administrator/.julia/packages/HSL/X5ozr/deps/usr/lib/libhsl_ma97.dylib, 0x0001): Library not loaded: @rpath/libblastrampoline.5.dylib
    Referenced from: /Users/administrator/.julia/packages/HSL/X5ozr/deps/usr/lib/libhsl_ma97.0.dylib
    Reason: tried: '/Users/administrator/actions-runner/_work/_tool/julia/1.6.7/x64/lib/julia/julia/libblastrampoline.5.dylib' (no such file), '/Users/administrator/actions-runner/_work/_tool/julia/1.6.7/x64/lib/julia/libblastrampoline.5.dylib' (no such file), '/Users/administrator/actions-runner/_work/_tool/julia/1.6.7/x64/bin/../lib/libblastrampoline.5.dylib' (no such file), '/usr/local/lib/libblastrampoline.5.dylib' (no such file), '/usr/lib/libblastrampoline.5.dylib' (no such file)
  Stacktrace:
    [1] Ma97_Control{Float64}(; print_level::Int64, unit_diagnostics::Int64, unit_error::Int64, unit_warning::Int64)
      @ HSL ~/.julia/packages/HSL/X5ozr/src/hsl_ma97.jl:115
    [2] Ma97_Control
      @ ~/.julia/packages/HSL/X5ozr/src/hsl_ma97.jl:90 [inlined]
    [3] ma97_csc(n::Int64, colptr::Vector{Int32}, rowval::Vector{Int32}, nzval::Vector{Float64}; kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
      @ HSL ~/.julia/packages/HSL/X5ozr/src/hsl_ma97.jl:327
    [4] ma97_csc
      @ ~/.julia/packages/HSL/X5ozr/src/hsl_ma97.jl:327 [inlined]
```

The tests are passing with julia 1.7 and nightly.

**Comment by amontoison** [comment]
Did you compile it on Mac?
The extension of the shared library is `dylib`.
I also don't understand why it's linked with `libblastrampoline`, it should use `lopenblas` for Julia v1.6.
Can you add the `main` version of HSl.jl and test again?

**Comment by amontoison** [comment]
Sorry, I missed that you added CI scripts...
I suppose that Ma97 was not recompiled on the M1 when you changed the Julia version. I fixed this issue but we need a new release of HSL.jl

**Comment by amontoison** [comment]
Can you open a PR in HSL.jl to do a new release?

**Review by amontoison — APPROVED** [review]

**Comment by geoffroyleconte** [comment]
Thanks @amontoison !

**Pull request merged**
